# ===================================================================
# 分布式文件系统FastDFS配置
# ===================================================================
fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
#    - 10.1.5.85:22122
#    - 10.1.5.86:22122

spring:
  rabbitmq:
    addresses: 127.0.0.1:5672,127.0.0.1:5673,127.0.0.1:5674
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    connection-timeout: 30000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 3
        max-concurrency: 5
        prefetch: 150
    template:
      mandatory: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: h2
    password: h2
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update