# ===================================================================
# 分布式文件系统FastDFS配置
# ===================================================================
fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
#    - 10.1.5.85:22122
#    - 10.1.5.86:22122

spring:
  rabbitmq:
    addresses:
    username: admin
    password: adminmq
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    connection-timeout: 30000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 3
        max-concurrency: 5
        prefetch: 150
    template:
      mandatory: true
